spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/valen_auto
spring.datasource.username=postgres
spring.datasource.password = Qw1Er2Ty

spring.jpa.hibernate.ddl-auto=update